name: build

on: [workflow_dispatch, push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        env:
          CC: clang
        run: |
          mkdir build
          cd build
          cmake ..
          make -j $(nproc)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            build/src/al-search
            build/src/mizuna-utils
            build/src/al-config
  
  build-windows:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        env:
          CC: clang
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 && cmake --build . --config Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-build
          path: |
            build/Release/al-search.exe
            build/Release/mizuna-utils.exe
            build/Release/al-config.exe
